### ISSUE TITLE
convert doesn't close file

### ISSUE THREAD

**Issue by flwyd** [ecopony/ruby-pota-csv-to-adif#4]
Rather than installing this as a gem, I ran an interactive `irb` session, `require`d the file in `lib`, and called
```ruby
log = ::PotaCsvToAdif::LogFile.new('my.csv')
log.convert
```
This resulted in an empty `my.adi` file until I exited the interpreter, which flushed the written data to disk and closed the output file.

`convert` should ensure the output file is closed, possibly by [passing a block to File.open](https://ruby-doc.org/core-2.5.0/File.html#method-c-open).

**Comment by ecopony** [comment]
Fixed with https://github.com/ecopony/ruby-pota-csv-to-adif/pull/5
